[package]
name = "argi"
version = "0.1.0"
description = "The simple cli library"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = ["Owen Griffiths <root@ogriffiths.com>"]
edition = "2018"
